return {
	walkSpeeds = {
		idle = 7,
		run = 20,
		sneak = 6,
		spit = 5,
		crowdControl = 6,
	},

	ranges = {
		walk = 120,
		sneak = 60,
		run = 80,
		nearTarget = 12.5,

		attack = 4,

		inversedRetreat = 300,

		lungeMinimum = 25,
		lungeMaximum = 35,

		toRunAndScreamMinimum = 30,
		superSonic = 65,

		strafeFar = 70,
		strafeClose = 10,
	},

	pathDistanceTolerance = 3,
	pathComputeIntervalSeconds = 0.25,
	pathRecomputeDistance = 4,

	detectionFov = 125,

	flashstepCooldownSeconds = 2,

	minimumMoveVelocity = 0.1,
	speedLerpRate = 8,
}
