return {
	maxTime = 2,

	distance = 35,
	minimumDistance = 6,

	turnSpeed = 22.5,
	maxTurnAlpha = 0.25,

	directionCorrectionDot = 0.65,
	directionCorrectionAlpha = 0.2,

	carryOver = 6,
	carryOverSlowdownSeconds = 1,

	landingDelaySeconds = 0.8,

	wallCheckDistance = 6,
	minimumWallCheckDistance = 4,

	hitboxSizeScale = 0.7,
	hitboxUpdateIntervalSeconds = 0.05,
	hitboxOffsetStuds = 1,
	hitboxVelocityPredictionDivisor = 25,

	statePollIntervalSeconds = 0.01,

	lungeSpeedTweenSeconds = 2.35,
	lungeSpeedMultiplier = 2.6,

	minimumLungeSpeed = 48,
	stopSpeedThreshold = 0.1,
	trackFadeSeconds = 0.1,
}
