return {
	backhandPropCooldownSeconds = 2,
	attackCooldownSeconds = 0.6,
	lungeCooldownSeconds = 15,
	spitCooldownSeconds = 15,
	screamCooldownSeconds = 15,
	superSonicCooldownSeconds = 40,
	heavyStunCooldownSeconds = 20,
	crowdControlDurationSeconds = 30,
	damageLogResetSeconds = 15,

	sneakToLungeDistance = 15,

	lightDamageMinimum = 12,
	lightDamageMaximum = 14,

	heavyDamageMinimum = 16,
	heavyDamageMaximum = 19,

	pushDamage = 5,
	pushRagdollTime = 2,
	pushKnockbackForce = 25,
	pushKnockbackLift = 8,
	pushKnockbackDuration = 0.15,

	spitChance = 0.25,
	spitBlockedChanceMultiplier = 0,
	spitBlockStreakThreshold = 2,
	spitCrowdSizeThreshold = 1, --4?
	spitCrowdSizeDelay = 0.4,

	crowdControlDamageThreshold = 300,
	playersNearbyToCrowdControl = 1, --2

	--// this is for the strafing stuff for when the target is charging a weapon
	rushChance = 0.15,
	rushCooldownSeconds = 4,
	rushDuration = 2,
}
