local attributeConstants = {
	character = {
		canRegen = "CanRegen",
		exhausted = "Exhausted",
		firstPerson = "FirstPerson",

		holdingSprint = "HoldingSprint",

		injured = "Injured",
		sprinting = "Sprinting",
		crouching = "Crouching",

		stamina = "Stamina",

		staminaMax = "StaminaMax",
		staminaMin = "StaminaMin",
	},

	tool = {
		aiming = "Aiming",
		armFollow = "ArmFollow",
		handFollow = "HandFollow",
		leftArm = "LeftArm",
		recoilSequence = "RecoilSequence",

		currentAmmo = "CurrentAmmo",
		reserveAmmo = "ReserveAmmo",
		reloading = "Reloading",

		equipped = "Equipped",
		specialEquip = "SpecialEquip",
		toggled = "Toggled",

		type = "Type",
	},
}

return attributeConstants
